### ISSUE TITLE
问题反馈和临时使用的建议

### ISSUE THREAD

**Issue by yjn140** [Kaoruha/YunZhanDownloader#2]
我遇到在判断size的位置会报错。然后我看了一下图片地址链接获取还能用，反正也是帮老师下载，给点建议给其他人，如果你也需要急用的话。

<img width="1626" alt="image" src="https://github.com/user-attachments/assets/98979cff-2824-4fed-a517-d00e32c872dd">
就是我直接把那两句注释掉，然后改成打印图片地址语句，丢到dowine4或者迅雷下载就可以了。

**Comment by yjn140** [comment]
```python
import os
import requests
from PIL import Image
from io import BytesIO

def download_and_save_as_webp(url_file, download_dir):
    # 确保下载目录存在
    if not os.path.exists(download_dir):
        os.makedirs(download_dir)

    # 读取包含URL的文件
    with open(url_file, 'r', encoding='utf-8') as file:
        urls = file.readlines()

    count = 1  # 文件名计数，从1开始

    for url in urls:
        url = url.strip()  # 去除多余的空格和换行符
        if not url:
            continue

        try:
            # 下载图片
            response = requests.get(url)
            response.raise_for_status()  # 如果请求失败，将抛出异常

            # 使用PIL处理图片数据
            img = Image.open(BytesIO(response.content))

            # 生成保存的文件名
            webp_filename = f"{count:03d}.webp"  # 按顺序重命名
            file_path = os.path.join(download_dir, webp_filename)

            # 保存为 webp 格式
            img.save(file_path, 'WEBP')
            print(f"图片已保存为: {file_path}")

            # 递增计数
            count += 1

        except Exception as e:
            # 如果出现问题，跳过当前链接并打印错误
            print(f"跳过链接 {url}，错误信息: {e}")

# 调用函数，传入文件路径和保存目录
download_and_save_as_webp('site.txt', 'downloads')
```

用这个下载保存也行

**Comment by Kaoruha** [comment]
能麻烦贴一下报错信息么, 这个项目当时是帮朋友下载一个几百页的文档用的的, 没有测试很多案例.

**Comment by yjn140** [comment]
> 能麻烦贴一下报错信息么, 这个项目当时是帮朋友下载一个几百页的文档用的的, 没有测试很多案例.

main.py代码是这样的

```python
import time
import os
import pyautogui
import random
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.chrome.service import Service

out_dir = "output"
os.system(f"mkdir {out_dir}")
url = "https://book.yunzhan365.com/waxqf/vxxk/mobile/index.html#wk-popup"
max_page = 1018

service = Service("/Users/song/Desktop/YunZhanDownloader/chromedriver")

driver = webdriver.Chrome(service=service)

driver.get(url)

page = 1


max_try = 3


def download_img():
    global page
    x_filter = f"//html/body/div[@id='tmpContainer']/div[@id='bookContainer']/div[@class='book'][1]/div[@id='pageMask{page}']/div[@id='page{page}']/div[@class='side-content']/div[@class='side-image']"
    ele = driver.find_element(By.XPATH, x_filter)
    ele = ele.find_element(By.TAG_NAME, "img")
    pic_url = ele.get_attribute("src")

    try_time = 0
    while try_time < max_try:
        try_time += 1



        # 这个位置
        # print(pic_url)
        os.system(f"wget {pic_url} -O {out_dir}/{page}.jpg")
        size = os.stat(f"{out_dir}/{page}.jpg").st_size






    page += 1

time.sleep(5)

download_img()
while True:
    pyautogui.press("right")
    time.sleep(1)
    download_img()
    time.sleep(0.2)
    download_img()
    time.sleep(0.2)

    if page >= max_page:
        break


driver.quit()
```

报错是这样的

```
/Users/song/Desktop/YunZhanDownloader/venv/lib/python3.9/site-packages/urllib3/__init__.py:34: NotOpenSSLWarning: urllib3 v2.0 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(
mkdir: output: File exists
sh: 1730899388: command not found
Traceback (most recent call last):
  File "/Users/song/Desktop/YunZhanDownloader/main.py", line 47, in <module>
    download_img()
  File "/Users/song/Desktop/YunZhanDownloader/main.py", line 38, in download_img
    size = os.stat(f"{out_dir}/{page}.jpg").st_size
FileNotFoundError: [Errno 2] No such file or directory: 'output/1.jpg'
```

有可能是系统不同，路径写法不同吧。我是没明白刚写入的文件为啥找不到。我也是急着用，调试看了一下pic_url参数获取到了我就不管那么多了。操控chrome的时候，不注释掉size那两行，翻页那一步都没到，就报错推出了。浏览器和驱动是最新最新版本。

还有，获取到的pic_url后面接了一个?x-oss-process=image/resize,h_784,w_572/sharpen,100&1730899388，这玩意会压缩画质，要去掉。

https://book.yunzhan365.com/waxqf/vxxk/files/large/a86483d682efd0be10e0e8540826ac85.webp?x-oss-process=image/resize,h_784,w_572/sharpen,100&1730899388

**Comment by yjn140** [comment]
哦还有，我改成打印出来的链接，会每个重复了三次，我也是写了个简单的脚本按顺序去重。

```python
def remove_duplicate_lines(file_path):
    # 读取文件内容
    with open(file_path, 'r', encoding='utf-8') as file:
        lines = file.readlines()

    # 使用一个集合来追踪已经出现过的行
    seen = set()
    unique_lines = []

    for line in lines:
        if line not in seen:
            unique_lines.append(line)
            seen.add(line)

    # 将去重后的内容写回文件
    with open(file_path, 'w', encoding='utf-8') as file:
        file.writelines(unique_lines)

    print(f"去重后的内容已经保存到 {file_path} 文件中")

# 调用函数，传入文件路径
remove_duplicate_lines('site.txt')
```

**Comment by yjn140** [comment]
这是对应那本内容的网址https://book.yunzhan365.com/waxqf/vxxk/mobile/index.html#wk-popup

**Comment by Kaoruha** [comment]
看起来像是windows文件系统解析是按\分割linux的/的问题 
a8e933ce280121cc7e52c9564960580891ab39c7 尝试了修复，不过身边没有可用的windows系统没有测试。
